name: aetos
description: Aetos Team App

publish_to: 'none'

version: 4.1.0+410000

environment:
  sdk: ">=3.5.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  material: ^1.0.0+2
  rss_dart: ^1.0.10
  shared_preferences: ^2.3.3
  provider: ^6.1.1
  xml: ^6.5.0
  excel: ^4.0.6
  new_version_plus: ^0.0.12
  url_launcher_android: ^6.3.14
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/splashscreen.png
    - assets/punten.json
    - assets/zaaldienst.json
