name: aetos
description: Aetos Team App

publish_to: 'none'

version: 5.4.1+540001

environment:
  sdk: ">=3.5.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  material: ^1.0.0+2
  rss_dart: ^1.0.12
  shared_preferences: ^2.3.5
  provider: ^6.1.1
  xml: ^6.5.0
  excel: ^4.0.6
  new_version_plus: ^0.1.0
  google_fonts: ^6.2.1
  flutter_html: ^3.0.0
  mailto: ^2.0.0
  url_launcher: ^6.3.1
  #device_info_plus: ^11.5.0
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.1+1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  image_path_android: "res/icon-710x599-android.png"
  image_path_ios: "res/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "res/icon-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "res/icon-foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "res/icon-monochrome-432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "res/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "res/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "res/icon-1024x1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/splashscreen.png
    - assets/punten.json
    - assets/zaaldienst.json
    - assets/images/
