name: aetos
description: Aetos Team App

publish_to: 'none'

version: 3.8.0+380000

environment:
  sdk: '>=2.19.4 <=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  material: ^1.0.0+2
  rss_dart: ^1.0.9
  shared_preferences: ^2.2.3
  provider: ^6.1.1
  xml: ^6.5.0
  excel: ^4.0.3
  new_version_plus: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/splashscreen.png
    - assets/zaaldienst.json
